version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-gosat
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - gosatcredito

  web:
    image: nginx:stable
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gosatcredito

  db:
    image: mariadb:10.6
    container_name: laravel-dbgosat
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: creditogosat
      MYSQL_USER: usergosat
      MYSQL_PASSWORD: laravelgosat
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - gosatcredito

volumes:
  dbdata:

networks:
  gosatcredito:
    driver: bridge
